apiVersion: v1
kind: Service
metadata:
  name: bookmyshow-service
spec:
  selector:
    app: bookmyshow
  ports:
    - protocol: TCP
      port: 5000
      targetPort: 5000
      nodePort: 30255
  type: NodePort
